version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
    restart: always

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 8080:8080
    restart: always
    
